spring:
  application:
    name: ai-web-generator-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AI_WEBSITE_GENERATOR
    username: 'root'
    password: ''
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.lcy.aiwebgenerator.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

